### ISSUE TITLE
Someone who knows Zuul needs to review our Gearman implementation

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/hoist#104]
gearman-job-server role runs gearman as a daemon so we can monitor instead of having zuul boot it, outside of zuul. Justification is that looking at mergers requires a check to see how many are listening, if zuul controls this the monitoring could be flaky.

There is a possible issue with gearman job server vs geard. Geard doesn't work the way zuul expects it to so we need to use the python one.

Question: Can you tell zuul to use a separate gear? it's been working so far...

**Comment by nibalizer** [comment]
We need to use the python based gearman server. Using a standalone server is fine.

We need to use the ``geard`` from the ``python-gear`` package instead of what we are currently using.

**Comment by missaugustina** [comment]
This issue was moved to BonnyCI/projman#24
