### ISSUE TITLE
Fails to deploy dd-agent on bastion

### ISSUE THREAD

**Issue by jamielennox** [BonnyCI/hoist#13]
The bastion ansible isn't executed with a secrets.yml file, this is only in the cideploy user. This means it fails on the bastion with

> fatal: [contrasjc-bastion]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'secrets' is undefined"}

We probably need to store secrets outside the cideploy user, maybe ssh keys as well (although ssh keys are less important now we're on a public github).

**Comment by jamielennox** [comment]
@j2sol ping

**Comment by j2sol** [comment]
Pretty sure this got fixed. Re-open if not.
