### ISSUE TITLE
zuul worker nodes fall off the radar

### ISSUE THREAD

**Issue by j2sol** [BonnyCI/hoist#147]
Something we're doing in our fast and furious debugging is causing existing nodepool nodes which are zuul workers for given jobs (like echo-true) are falling off the radar. Nodepool knows about them, but zuul does not and jobs will sit indefinitely until we manually boot the nodepool node. We're not doing something right here.

**Comment by missaugustina** [comment]
This issue was moved to BonnyCI/projman#23
