### ISSUE TITLE
Add datadog checks for services

### ISSUE THREAD

**Issue by j2sol** [BonnyCI/hoist#15]
Identify services and implement checks in them.

http://docs.datadoghq.com/guides/agent_checks/

http://docs.datadoghq.com/monitoring/

https://docs.ansible.com/ansible/datadog_monitor_module.html

**Comment by j2sol** [comment]
#25 is related to this.

**Comment by jesusaurus** [comment]
#66 is related to this

**Comment by missaugustina** [comment]
This issue was moved to BonnyCI/projman#22
