### ISSUE TITLE
Improve secrets management

### ISSUE THREAD

**Issue by j2sol** [BonnyCI/hoist#18]
Currently we have a plain text secrets file that we hand copy from bastion to bastion. This is a bit scary as it sits in plain text on whatever filesystem it happens to be copied to.

I propose we instead encrypt this file with ansible vault. This allows the file to remain encrypted at rest, and we simply have to write a passphrase to the filesystem of the bastions so that cron executed jobs can read the file. Any backup we make of the file will be encrypted.

We'll put aside discussion of where to store/backup this file for a later discussion.

The new bastion flow would be:

1) Use hoist to boot new instance with an ssh key you can use
2) Log into new instance and put secrets file in place and write passphrase to expected path
3) execute remainder of hoist on the bastion, enabling it to self-update

As new people are on-boarded we can communicate the vault passphrase to them. As people leave, we can rotate the secrets inside the vault, and rekey the value itself, communicating the new passphrase to the remainders.

Part of this is we will need to track all the secrets and use Ansible to write them out to the filesystem, rather than hand copying a bunch of files.

- [ ] deploy ssh keys

- [x] clouds.yaml

**Comment by j2sol** [comment]
Secrets are now vault protected on the filesystem, with just a passphrase written out. Other work related to this issue can continue.

**Comment by missaugustina** [comment]
This issue was moved to BonnyCI/projman#37
