### ISSUE TITLE
Improve pip role

### ISSUE THREAD

**Issue by j2sol** [BonnyCI/hoist#20]
There are a couple issues with pip role that should be addressed:

- [ ] pip install script is downloaded and executed without any validation
- [ ] pip install script is ran every playbook execution

We should discuss how to address these in the near future.

**Comment by SpamapS** [comment]
Vendored and done

**Comment by rattboi** [comment]
Vendored, but needs some improvements.

**Comment by missaugustina** [comment]
This issue was moved to BonnyCI/projman#36
