### ISSUE TITLE
deploy user ssh keys need to live somewhere

### ISSUE THREAD

**Issue by gandelman-a** [BonnyCI/hoist#33]
this could be part of https://github.com/BonnyCI/hoist/issues/18

when provisioning a bastion from scratch, the deploy user (currently 'cideploy') needs ssh keys generated or installed so that it can reach the infrastructure its managing (the zuul and nodepool nodes)

we can add this to secrets.yml (or whatever that turns into), but the cideploy user is managed as a normal bastion_user in roles/bastion/, and not as a special cased deploy user with ssh key management.

**Comment by missaugustina** [comment]
This issue was moved to BonnyCI/projman#35
