### ISSUE TITLE
Add Nodepool monitoring to data dog

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/hoist#62]
Currently need to know if nodepool is running or not. Nodepool provides monitoring data via statsd. We don't yet know what additional monitoring data we want.

Addtionally: are nodepool images building?

**Comment by jamielennox** [comment]
#64 covers some of the statsd part of this as it's basically the same as zuul. For additional monitoring it looks like there is a nodepool webapp status at http://locahost:8005/image-list and /dib-image-list. This port or bind ip is not configurable and we should fix that upstream. Also the response is exactly the same as the PrettyTable formatted "nodepool image-list" which is annoying to parse from a web request but would give us a request based handler like the ZuulCheck.

**Comment by missaugustina** [comment]
Working on getting a local hoist VM spun up so I can work on this

**Comment by missaugustina** [comment]
VM thing is not happening so just working on adding the role and following the pattern for the dd-zuul stuff.

**Comment by missaugustina** [comment]
I have changes for this I will push when I get a chance. I still need to test it on a working VM.

**Comment by missaugustina** [comment]
This issue was moved to BonnyCI/projman#32
