### ISSUE TITLE
Need an easy way to test changes locally

### ISSUE THREAD

**Issue by jesusaurus** [BonnyCI/hoist#72]
Developers should have an easy and simple means of local testing.

**Comment by missaugustina** [comment]
I went ahead and assigned this since it sounds like you're playing around with Vagrant to make this a reality. I'm adding myself to it too since I'm trying to better document the setup steps.

**Comment by j2sol** [comment]
Some things I'm running into.

- monitoring calls that hit data dog will fail unless a secret key is in place. Need to skip those, but do the rest of monitoring.
- nodepool role default references a cloud not configured in example secrets
- bastion role requirement hardcodes a cloud not configured in example secrets

**Comment by j2sol** [comment]
This may be fixed, or partially fixed, by #93

**Comment by missaugustina** [comment]
This issue was moved to BonnyCI/projman#31
