### ISSUE TITLE
need to validate deployment against a gerrit

### ISSUE THREAD

**Issue by gandelman-a** [BonnyCI/hoist#75]
before messing with github integration, we need to point the CI deployment at an existing gerrit to validate basic functionality of v2.5: event processing, tests running, results posting, nodepool nodepooling.

nibz suggests we can use review.portbleu.com as a sandbox. we need a bot user created there and a preferably a project to run against.

**Comment by nibalizer** [comment]
I've created a service user on a gerrit. The zuul user has an ssh key authorized on this gerrit user.

**Comment by missaugustina** [comment]
This issue was moved to BonnyCI/projman#30
