### ISSUE TITLE
Improve security group settings

### ISSUE THREAD

**Issue by j2sol** [BonnyCI/hoist#91]
Currently every CI node we create in `create-hosts.yml` is getting the `default` security group. Additionally the `default` group has been set to allow incoming port 22 and 80 across the board, which is inappropriate.

If we must have 22, I propose we create a new "default" security group for our systems that opens 22, and we create additional security groups that are appropriate for each node that may have a service that requires external to the private network incoming connections to a particular service.

**Comment by j2sol** [comment]
I just opened `8001` in the default group, an incoming port for zuul getting web hooks.

**Comment by missaugustina** [comment]
This issue was moved to BonnyCI/projman#29
